server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
			globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: simulate-service
          uri: lb://simulate-service
          predicates:
            - Path=/simulate/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/requests/**
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluate/**
        - id: request-tracking-service
          uri: lb://request-tracking-service
          predicates:
            - Path=/requestTracking/**