server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: simulate-service
          uri: lb://simulate-service
          predicates:
            - Path=/simulate/**
        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/users/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/requests/**
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluate/**
        - id: request-tracking-service
          uri: lb://request-tracking-service
          predicates:
            - Path=/requestTracking/**
